apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-standalone-vlan0
  namespace: kube-system
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "macvlan-standalone",
        "plugins": [
            {
                "type": "macvlan",
                "master": "eth0",
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "veth",
                "service_hijack_subnet": ["10.233.0.0/18","fd00:10:96::/112"],
                "overlay_hijack_subnet": [""10.244.0.0/16","fd00:10:244::/56"],
                "additional_hijack_subnet": [],
                "migrate_route": -1,
                "rp_filter": {
                    "set_host": true,
                    "value": 0
                },
                "skip_call": false
            }
        ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-standalone-vlan100
  namespace: kube-system
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "macvlan-standalone",
        "plugins": [
            {
                "type": "macvlan",
                "master": "eth0.100",
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "log_level": "DEBUG",
                    "log_file_path": "/var/log/spidernet/spiderpool.log",
                    "log_file_max_size": 100,
                    "log_file_max_age": 30,
                    "log_file_max_count": 10
                }
            },{
                "type": "veth",
                "service_hijack_subnet": ["10.233.0.0/18","fd00:10:96::/112"],
                "overlay_hijack_subnet": [""10.244.0.0/16","fd00:10:244::/56"],
                "additional_hijack_subnet": [],
                "migrate_route": -1,
                "rp_filter": {
                    "set_host": true,
                    "value": 0
                },
                "skip_call": false
            }
        ]
    }